export const GET_RECOMMENDATIONS_START = "SMS/GET_RECOMMENDATIONS_START";
export const GET_RECOMMENDATIONS_SUCCESS = "SMS/GET_RECOMMENDATIONS_SUCCESS";
export const GET_RECOMMENDATIONS_FAILURE = "SMS/GET_RECOMMENDATIONS_FAILURE";

export const GET_PRODUCTS_START = "SMS/GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "SMS/GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "SMS/GET_PRODUCTS_FAILURE";

export const ADD_TO_CART = "SMS/ADD_TO_CART";